# GamerX OS makepkg defaults
# Parallel compression, parallel make, modern compression.

MAKEFLAGS="-j$(nproc)"
COMPRESSXZ=(xz -c -z - --threads=0)
COMPRESSZST=(zstd -c -z -q --threads=0 -)
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'
